In [1]:
import pandas as pd
import numpy as np


## Simulations  = Monte Carlo

## How to run a simulation with python/numpy/pandas
1. Figure out a way to represent our data
2. Create a matrix of random data, rows= simulations, columns = trial
     - For Ex, rolling 2 dice 10,000 times means rows = 10000 and columns  = 2 b'c we roll 2 dice ea time
3. Apply an aggregate function, row-wisde to get the results of the simulation
4. Apply a final aggregate to get our probability.     

In [4]:
# let's answer questions experimentally reather than theoretically
# What's the prob of flipping HEADS on a coin?

# let's flip a coin 100,000 times and figure our the prob of flipping HEADS

# let's find a way to rep our data
outcomes = ["Heads", "Tails"]
n_simulations = 100_000

flips = np.random.choice(outcomes, size = n_simulations)

# after flipping 100k coins, our experimentsal prob of flipping heads is:
(flips == "Heads")

array([ True, False, False, ...,  True,  True, False])

In [5]:
(flips == "Heads").mean()

0.49844

In [7]:
outcomes = ["Heads", "Tails"]
n_simulations = 1_000_000

flips = np.random.choice(outcomes, size = n_simulations)

(flips == "Heads").mean()

0.499538

In [12]:
#another ex
# what is the prob of rolling a 5 on a 6-sided die?

#1. represent our data's outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#2. trials: create the data
n_simulations = 10_000

rolls = np.random.choice(outcomes, size=n_simulations)

#what are the changes we roll a 5?
(rolls == 5).mean()

0.1747

In [13]:
#what is the prob we'll roll a 5 or 6 on a 6-sided die?
(rolls >= 5).mean()

0.3382

In [14]:
#what is the prob we'll roll less than a 3 on a 6-sided die?
(rolls < 3).mean()

0.3352

In [15]:
#what is the prob we'll roll anything other than 3 on a 6-sided die?
(rolls != 3).mean()

0.8368

## Let's roll 2 dice at once
1. figure out a way to rep the data
2. create a matrix of random data, row=simulations, columns=trials
3. apply an aggregate row-wise to get the result oif ea simulation
4. apply a final aggregate (prob the .mean) to get out probability


In [17]:
# what are the odds of rolling Snake Eyes on 2 die?

#1. rep our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#2. create a matrix of randon data where rows=simulations, columns-trials

#simulations = # of times we reun the experiment
# trials = # of things in ea experiment
n_simulations = 1_000_000
n_trials = 2# b'c we're rolling 2 dice with ea experiment

#size arguement can set our simulation and trial size
rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))
rolls

array([[2, 3],
       [3, 6],
       [2, 3],
       ...,
       [4, 2],
       [5, 4],
       [6, 1]])

In [18]:
#3. apply an aggregate row-wise
#axis=1 means sum across the rows
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls

array([5, 9, 5, ..., 6, 9, 7])

In [19]:
#axis=0::: COLUMNS
#rolls.sum(axis=0)

#if you don't put an axis, it defaults to 0

array([3498326, 3499122])

In [20]:
#4. apply a final aggregate
(sum_of_rolls == 2).mean()

#add up all the times an experiment/simulation produces the sum of two(Snake Eyes)

0.027678

In [21]:
theoretical = 1/6 * 1/6

print(f"Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is {theoretical}")

Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is 0.027777777777777776


In [23]:
# what is the prob of rolling a 7 on 2 die?
# 1+6, 2+5, 3+4, 4+3, 5+2, 6+1 

#1. rep out outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#2. generate matrix of random outcomes, simulations=rows, trials=columns
#size=(simulations, trials)
#sixe(experiments, number_of_dice per experi)

rolls = np.random.choice(outcomes, size=(10_000, 2))

#3. apply row-wise aggregate
#axis=1, to apply sum to rows
sum_of_rolls = rolls.sum(axis=1)

(sum_of_rolls == 7).mean()

0.168

In [24]:
#possible sum outcomes from 2 die
x = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

#
y = [(sum_of_rolls == n).mean() for n in sum_of_rolls]

In [25]:
y

[0.0837,
 0.1104,
 0.1104,
 0.0809,
 0.0837,
 0.168,
 0.0544,
 0.1104,
 0.1413,
 0.1413,
 0.0809,
 0.0809,
 0.168,
 0.168,
 0.1413,
 0.0809,
 0.1343,
 0.0567,
 0.168,
 0.1413,
 0.1343,
 0.0809,
 0.0837,
 0.1343,
 0.1413,
 0.0567,
 0.1154,
 0.1413,
 0.1104,
 0.0809,
 0.1104,
 0.0837,
 0.168,
 0.1154,
 0.1104,
 0.168,
 0.0291,
 0.1104,
 0.0809,
 0.1413,
 0.1154,
 0.0837,
 0.0809,
 0.0809,
 0.168,
 0.1154,
 0.168,
 0.1104,
 0.1343,
 0.1343,
 0.1343,
 0.1413,
 0.0567,
 0.1413,
 0.1154,
 0.1343,
 0.0258,
 0.168,
 0.0809,
 0.0809,
 0.0567,
 0.1413,
 0.0837,
 0.1104,
 0.0809,
 0.1413,
 0.1413,
 0.1413,
 0.0837,
 0.0258,
 0.168,
 0.0837,
 0.1413,
 0.0291,
 0.168,
 0.1154,
 0.168,
 0.168,
 0.1413,
 0.168,
 0.0567,
 0.0291,
 0.168,
 0.1154,
 0.0291,
 0.1413,
 0.168,
 0.0567,
 0.1154,
 0.0837,
 0.168,
 0.1104,
 0.0544,
 0.0567,
 0.1154,
 0.168,
 0.1413,
 0.0258,
 0.1343,
 0.1343,
 0.1154,
 0.0837,
 0.1343,
 0.0291,
 0.1154,
 0.168,
 0.0837,
 0.1154,
 0.0291,
 0.1413,
 0.0544,
 0.1343,
 0.0837,
 0